Repository retaildevcrews/pib-cli, pull requests merged in 2022-03, with the labels that each got.

#34 flt bug fixes
  .devcontainer/.vscode/launch.json
  .devcontainer/.vscode/settings.json
  .devcontainer/.vscode/tasks.json
  .devcontainer/Dockerfile
  .devcontainer/on-create.sh
  .devcontainer/post-start.sh
  .gitignore
  bin/.kic/gitops-config.templ
  digital-twin/ips
  fleet/bin/.kic/commands/reset
  src/kic/.kic/gitops-config.templ
  src/kic/cmd/fleet/create.go
  src/kic/cmd/fleet/fleet.go
  src/kic/cmd/fleet/pull.go
  src/kic/cmd/fleet/ssh.go
  src/kic/cmd/fleet/token.go
  src/kic/utils/utils.go
Labels: Bug, TechnicalDebt

#36 updated flt create
  .devcontainer/on-create.sh
  assets/akdc.templ
  assets/gen-gitops/200.tsv
  assets/gen-gitops/Program.cs
  assets/gen-gitops/gen-gitops.csproj
  assets/gen-gitops/red.tsv
  bin/.kic/build.boa
  bin/.kic/check.boa
  bin/.kic/cluster.boa
  bin/.kic/commands/check/all
  bin/.kic/docs.boa
  fleet/bin/.kic/check.boa
  fleet/bin/.kic/cluster.boa
  fleet/bin/.kic/root.boa
  src/kic/.kic/build.boa
  src/kic/.kic/check.boa
  src/kic/.kic/cluster.boa
  src/kic/.kic/commands/check/all
  src/kic/.kic/docs.boa
  src/kic/Makefile
  src/kic/boa/boa.go
  src/kic/boa/boa_test.go
  src/kic/boa/cfmt/cfmt.go
  src/kic/boa/cfmt/cfmt_test.go
  src/kic/boa/io.go
  src/kic/boa/io_test.go
  src/kic/boa/shell.go
  src/kic/boa/shell_test.go
  src/kic/cmd/fleet/check/aioa.go
  src/kic/cmd/fleet/check/check_test.go
  src/kic/cmd/fleet/check/dapr.go
  src/kic/cmd/fleet/check/flux.go
  src/kic/cmd/fleet/check/heartbeat.go
  src/kic/cmd/fleet/check/logs.go
  src/kic/cmd/fleet/check/radius.go
  src/kic/cmd/fleet/check/retries.go
  src/kic/cmd/fleet/check/setup.go
  src/kic/cmd/fleet/create.go
  src/kic/cmd/fleet/delete.go
  src/kic/cmd/fleet/exec.go
  src/kic/cmd/fleet/fleet.go
  src/kic/cmd/fleet/fleet_test.go
  src/kic/cmd/fleet/groups.go
  src/kic/cmd/fleet/patch.go
  src/kic/cmd/fleet/pull.go
  src/kic/cmd/fleet/ssh.go
  src/kic/cmd/fleet/sync.go
  src/kic/cmd/fleet/token.go
  src/kic/cmd/root.go
  src/kic/cmd/root_test.go
  src/kic/cmd/targets/targets-list.go
  src/kic/cmd/targets/targets-push.go
  src/kic/cmd/targets/targets.go
  src/kic/cmd/targets/targets_test.go
  src/kic/cmd/test/test-integration.go
  src/kic/cmd/test/test-load.go
  src/kic/cmd/test/test.go
  src/kic/cmd/test/test_test.go
  src/kic/main_test.go
  src/kic/utils/utils.go
Labels: DevExperience

#43 Demo feedback
  .devcontainer/on-create.sh
  .devcontainer/post-create.sh
  .devcontainer/post-start.sh
  digital-twin/README.md
  src/_kic
  src/kic/cmd/targets/targets-deploy.go
  src/kic/cmd/targets/targets-push.go
  src/kic/cmd/targets/targets.go
  src/kic/cmd/targets/targets_test.go
  src/kic/cover.html
  src/kic/cover.out
Labels: InternalFeedback

#44 Fix for Innerloop test runs `kic test`
  .devcontainer/devcontainer.json
  .devcontainer/grafana.db
  .devcontainer/on-create.sh
  .devcontainer/post-create.sh
  .devcontainer/post-start.sh
  README.md
  bin/.akdc/commands/cluster/clean
  bin/.akdc/commands/cluster/deploy
  bin/.akdc/commands/cluster/jumpbox
  bin/.akdc/commands/dev/aioa
  bin/.akdc/commands/dev/imdb
  bin/.akdc/commands/dev/webv
  bin/.akdc/commands/local-check/all
  bin/.akdc/commands/local-check/grafana
  bin/.akdc/commands/local-check/heartbeat
  bin/.akdc/commands/local-check/imdb
  bin/.akdc/commands/local-check/prometheus
  bin/.akdc/commands/local-check/webv
  bin/.akdc/commands/test-integration
  bin/.akdc/commands/test-load
  bin/.akdc/commands/vm/test
  bin/.akdc/local.boa
  bin/.akdc/root.boa
  bin/.akdc/vm.boa
  digital-twin/README.md
  digital-twin/curl.http
  fleet/scripts/patch.sh
  fleet/scripts/test-integration
  fleet/scripts/test-load
  inner-loop/README.md
  inner-loop/curl.http
  inner-loop/deploy/aioa-local/aioa.yaml
  inner-loop/deploy/aioa/README.md
  inner-loop/deploy/aioa/aioa.yaml
  inner-loop/deploy/bootstrap/fluentbit/stdout-config.yaml
  inner-loop/deploy/bootstrap/namespaces.yaml
  inner-loop/deploy/bootstrap/prometheus/2-config-map.yaml
  inner-loop/deploy/imdb-local/imdb-local.yaml
  inner-loop/deploy/imdb/imdb.yaml
  inner-loop/deploy/namespace.yaml
  inner-loop/deploy/webv-local/webv-local.yaml
  inner-loop/deploy/webv/webv.yaml
  inner-loop/webv/baseline.json
  inner-loop/webv/imdb-baseline.json
  inner-loop/webv/imdb-benchmark.json
  iot-edge/README.md
  iot-edge/ips
  kfc-demo/demo.sh
  kfc-demo/ips
  src/kic/Makefile
  src/kic/cmd/root.go
  src/kic/cmd/test/test-integration.go
  src/kic/cmd/test/test-load.go
  src/kic/cmd/test/test_test.go
  src/kic/cover.html
  src/kic/cover.out
Labels: DevExperience

#45 updated kic test description
  src/kic/cmd/test/test-integration.go
  src/kic/cmd/test/test-load.go
  src/kic/cover.html
  src/kic/cover.out
Labels: Bug

#47 use kubernetes-in-codespaces for inner-loop
  .devcontainer/on-create.sh
  .devcontainer/post-create.sh
  README.md
  inner-loop/README.md
  inner-loop/curl.http
  inner-loop/deploy/bootstrap/fluentbit/account.yaml
  inner-loop/deploy/bootstrap/fluentbit/deployment.yaml
  inner-loop/deploy/bootstrap/fluentbit/log.yaml
  inner-loop/deploy/bootstrap/fluentbit/stdout-config.yaml
  inner-loop/deploy/bootstrap/grafana/datasource.yaml
  inner-loop/deploy/bootstrap/grafana/deployment.yaml
  inner-loop/deploy/bootstrap/heartbeat/heartbeat.yaml
  inner-loop/deploy/bootstrap/namespaces.yaml
  inner-loop/deploy/bootstrap/prometheus/1-clusterRole.yaml
  inner-loop/deploy/bootstrap/prometheus/2-config-map.yaml
  inner-loop/deploy/bootstrap/prometheus/3-prometheus-deployment.yaml
  inner-loop/deploy/bootstrap/webv-heartbeat/webv-hearbeat.yaml
  inner-loop/deploy/imdb-local/imdb-local.yaml
  inner-loop/deploy/imdb/imdb.yaml
  inner-loop/deploy/namespace.yaml
  inner-loop/deploy/webv-local/webv-local.yaml
  inner-loop/deploy/webv/webv.yaml
  inner-loop/webv/baseline.json
  inner-loop/webv/benchmark.json
  inner-loop/webv/heartbeat-baseline.json
  inner-loop/webv/heartbeat-benchmark.json
  inner-loop/webv/imdb-baseline.json
  inner-loop/webv/imdb-benchmark.json
Labels: DevExperience, TechnicalDebt

#49 updated codespaces
  .devcontainer/on-create.sh
  .devcontainer/post-create.sh
Labels: Bug

#50 updated kic CLI
  src/kic/cmd/root.go
Labels: Bug

#52 resolve now that KiC repo is updated
  .devcontainer/on-create.sh
Labels: TechnicalDebt

#55 add GitOps repo branch support
  .devcontainer/post-create.sh
  assets/akdc.templ
  src/kic/cmd/fleet/create.go
  src/kic/cmd/fleet/fleet_test.go
  src/kic/cover.html
  src/kic/cover.out
Labels: CustomerFeedback, DevExperience
