Repository retaildevcrews/pib-cli, pull requests merged in 2022-04, with the labels that each got.

#56 updated red-fleet commands
  .github/PULL_REQUEST_TEMPLATE.md
  digital-twin/setup-flux.sh
  red-fleet/create.sh
  red-fleet/curl-all.sh
  red-fleet/delete.sh
  src/kic/cmd/fleet/check/check.go
  src/kic/cmd/fleet/check/check_test.go
  src/kic/cmd/fleet/check/tlog.go
  src/kic/cmd/fleet/create.go
  src/kic/cover.html
  src/kic/cover.out
Labels: Bug

#65 updated for multi-repo
  .devcontainer/grafana.db
  .devcontainer/on-create.sh
  .devcontainer/post-create.sh
  README.md
  bin/.flt/commands/az-login
  bin/.flt/root.boa
  docs/CERTS.md
  docs/EngineeringPractices.md
  docs/WorkingAgreement.md
  docs/fleet.old.md
  pilot-fleet/create.sh
  pilot-fleet/curl-all.sh
  pilot-fleet/delete.sh
  pilot-fleet/ips
  red-fleet/README.md
  red-fleet/create.sh
  red-fleet/curl-all.sh
  red-fleet/delete.sh
  red-fleet/ips
  test-fleet/10-vms-ssl/create.sh
  test-fleet/10-vms-ssl/curl-all.sh
  test-fleet/10-vms-ssl/delete.sh
  test-fleet/10-vms/create.sh
  test-fleet/10-vms/delete.sh
  test-fleet/200-vms/create1.sh
  test-fleet/200-vms/create2.sh
  test-fleet/200-vms/delete.sh
  test-fleet/25-vms-ssl/create.sh
  test-fleet/25-vms-ssl/curl-all.sh
  test-fleet/25-vms-ssl/delete.sh
Labels: DevExperience

#106 moved commands to boa
  bin/.flt/root.boa
  src/kic/cmd/fleet/arcToken.go
  src/kic/cmd/fleet/fleet.go
  src/kic/cmd/fleet/fleet_test.go
  src/kic/cmd/fleet/patch.go
  src/kic/cmd/fleet/pull.go
  src/kic/cmd/fleet/sync.go
  src/kic/cmd/root.go
  src/kic/cover.html
  src/kic/cover.out
Labels: DevExperience, TechnicalDebt

#110 move akdc templ to .flt
  bin/.flt/fleet-vm.templ
  src/kic/cmd/fleet/create.go
  src/kic/cover.html
  src/kic/cover.out
Labels: DevExperience, TechnicalDebt

#125 update flt delete to check if rg exists
  src/kic/cmd/fleet/delete.go
Labels: Bug, TechnicalDebt

#126 reorganized docs
  .devcontainer/on-create.sh
  .github/EngineeringPractices.md
  .github/WorkingAgreement.md
  docs/fleet.old.md
  docs/images/arc.png
  docs/images/debug-akdc.png
Labels: TechnicalDebt

#151 update template
  bin/.flt/fleet-vm.templ
  vm/setup/akdc-config.sh
  vm/setup/akdc-dns.sh
  vm/setup/akdc-install.sh
  vm/setup/akdc-post.sh
  vm/setup/akdc-pre-arc.sh
  vm/setup/akdc-pre-flux.sh
  vm/setup/akdc-pre-k3d.sh
  vm/setup/akdc-private-repos.sh
  vm/setup/akdc-setup.sh
  vm/setup/arc-setup.sh
  vm/setup/flux-setup.sh
  vm/setup/k3d-setup.sh
Labels: DevExperience, TechnicalDebt

#163 script updates from fleet 210 testing
  bin/.flt/fleet-vm.templ
  vm/setup/akdc-config.sh
  vm/setup/akdc-dns.sh
  vm/setup/akdc-install.sh
  vm/setup/akdc-post.sh
  vm/setup/akdc-pre-arc.sh
  vm/setup/akdc-pre-flux.sh
  vm/setup/akdc-pre-k3d.sh
  vm/setup/akdc-private-repos.sh
  vm/setup/akdc-setup.sh
  vm/setup/arc-setup.sh
  vm/setup/flux-setup.sh
  vm/setup/k3d-setup.sh
Labels: Bug, DevExperience

#184 Support for private container registries
  vm/setup/k3d-setup.sh
  vm/setup/registries.templ
Labels: DevExperience

#198 add kic events command
  .devcontainer/post-start.sh
  bin/.kic/commands/events
  bin/.kic/root.boa
  vm/bin/.kic/commands/events
  vm/bin/.kic/root.boa
Labels: DevExperience

#216 updating setup
  bin/.flt/commands/env
  bin/.flt/commands/set-fleet
  bin/.flt/fleet-vm.templ
  bin/.flt/root.boa
  bin/.kic/commands/env
  bin/.kic/root.boa
  vm/setup/akdc-pre-k8s.sh
  vm/setup/akdc-setup.sh
  vm/setup/k8s-setup.sh
Labels: TechnicalDebt
